
require("dotenv").config()

module.exports = {
    auth_failed:"Authentication Failed",
    something_wrong:"Something wrong",
    errorMessage :'Oops! Something went wrong here...',
    request_invalid:"Your request is not valid",
    mobile_num_invalid:"Mobile Number is not valid",
    password_invalid:"Password must contain at least one letter, one number and one special character (!@#$%^&*)",
    enter_correct_password:"Please Enter correct Password",
    reset_password_link_sent_to_email:"Reset Password link sent to your registered Email",
    reset_password_success:"Reset password successfully",
    password_not_reset:"Password not able to reset",
    enter_old_password:"Please enter right old password",
    password_change_success:"Password Changed Successfully",
    new_password_not_same_as_old_password:"New Password must not be same as old password",
    pincode_invalid:"Pincode is not valid",
    org_not_found:"Organisation not found",
    org_list_not_found:"Organisation list not found",
    org_list_get:"Organisation list get successfully",
    email_not_verified:"Email is not verified, Please verify your email",
    email_not_register:"Email is not registered, Please register",
    user_login_success:"User login successfully",
    user_not_login:"User not able to login",
    user_profile_create:"User Profile created Successfully",
    user_profile_not_create:"User Profile not able to create",
    user_profile_already_create:"User Profile already created",
    user_profile_get:"User Profile get Successfully",
    user_profile_update:"User Profile has been updated successfully",
    user_profile_not_created:"User profile is not created",
    create_user_profile:"Please create User profile",
    user_not_found:"User not found",
    user_not_active:"User is not in active state. Please contact admin",
    user_exist_already:"User already Exist",
    user_type_admin:"User type should be super admin",
    user_created:"User created Successfully",
    user_not_create:"User not able to create",
    user_role_invalid:"User Role is not valid",
    user_type_invalid:"User Type is not Valid",
    user_profile_list:'User profile list get successfully.',
    tour_viewed:"Tour successfully viewed",
    user_already_register:"User details you have entered already registered",
    client_profile_get:'Client profile get successfully',
    client_profile_create:"Client Profile created successfully",
    client_profile_update:"Client Profile updated successfully",
    client_profile_not_create:"Client profile not able to create",
    client_profile_not_found:"Client Profile not found",
    client_profile_delete:"Client profile data delete successfully",
    client_status_change:"client status changed successfully",
    client_profile_approved_by_admin:"User Profile approved by admin successfully",
    state_get:"States get successfully",
    city_get:"cities get successfully",
    country_name_required:"country name required",
    state_not_found:"State Name not found",
    state_fips_required:"State fips code is required",
    accept_terms_invalid:"Accept Terms and condition is not valid",
    verify_your_email:"Please verify your email address",
    email_already_verified:"Email is already verified",
    email_verified:"Congratulations! Your email has been successfully verified",
    email_verify_to_login:"Please verify Email to login",
    token_missed:"Token is missing",
    token_invalid:"Token is not Valid",
    token_required:"Token is required",
    token_expire:"This token has been expired",
    google_register:"You are registered with google please log in with it",
    app_in_process_approve_by_admin:"Your application is in process, Please wait until Admin approved",
    app_reject:"Your application is rejected, Please contact admin",
    question_create:"Question created successfully",
    question_not_create:"Question could'nt created Something went wrong",
    question_bank_not_found:"Question bank could'nt find Something went wrong",
    question_bank_list_found:"Question bank list data get successfully",
    question_bank_list_not_found:"Question bank list data not found",
    token_for_auth:"You need to provide token for authentication",
    user_not_exist:"The user does not exists on this platform",
    user_unauthorized_to_access:"You are not authorized to access this response",
    section_found:'section list',
    section_create:'section created successfully',
    section_not_found:'section not found',
    status_change:'Status change Successfully',
    status_not_change:'status not change'
}